repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9  # Use the latest Ruff version
    hooks:
      - id: ruff
        args: [--fix]   # auto-fix lint issues
      - id: ruff-format # enforce Ruff formatter
